library(datarobot)
proj = datarobot::SetupProject('https://s3.amazonaws.com/datarobot_public_datasets/multiclass/GesturePhaseSegmentationRAW_v1_80.csv')
datarobot::UpdateProject(proj, workerCount = 20)
datarobot::SetTarget(proj, 'phase')
Sys.sleep(60)
models = datarobot::GetAllModels(proj)
pred_dat = datarobot::PredictionDatasetFromAsyncUrl('https://s3.amazonaws.com/datarobot_public_datasets/multiclass/GesturePhaseSegmentationRAW_v1_20.csv')
pred_job = datarobot::RequestPredictions(models[1], pred_dat)
preds = datarobot::GetPredictions(proj, pred_job)
